name: CI

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install (if package.json present)
        run: |
          if [ -f package.json ]; then npm ci || npm install; fi
      - name: Lint (if script present)
        run: |
          if [ -f package.json ] && npm run | grep -q "lint"; then npm run lint; else echo "No lint script"; fi
      - name: Test (if script present)
        run: |
          if [ -f package.json ] && npm run | grep -q "test"; then npm test --silent; else echo "No test script"; fi

